# Generated by Django 4.2.1 on 2023-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_clases', models.PositiveBigIntegerField()),
                ('fecha_inicio', models.PositiveIntegerField()),
            ],
        ),
    ]
