# Generated by Django 4.2.1 on 2023-05-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin_remove_plan_fecha_inicio_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.DateField(null=True)),
                ('limite_cupos', models.PositiveBigIntegerField()),
                ('cantidad_inscriptos', models.PositiveBigIntegerField()),
                ('estado_clase', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clase')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
