# Generated by Django 4.2.1 on 2023-05-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clase_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
