# Generated by Django 4.2.1 on 2023-05-15 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_clase_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
