# Generated by Django 4.2.1 on 2023-05-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_clase_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='id_clase',
            new_name='clase',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
