# Generated by Django 4.2.1 on 2023-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_id_clase_reserva_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clases_restantes',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
