# Generated by Django 4.2.1 on 2023-05-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cliente_clases_restantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clases_restantes',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plan'),
        ),
    ]
