# Generated by Django 4.2.1 on 2023-05-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cliente_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contraseña',
            new_name='password',
        ),
    ]
